language: python
python:
  - "3.9"

deploy:
  provider: heroku
  api_key:
    secure: "HYF/z1pyjETHlGuneA7rK654lqJcC3+5ZhC72xygQ8TtnvCG+XkVzAPnZz5UXKv9oQxsR07LNd4hQJD381/iEc7yG871TbZow33tfhbKjILqww5UoCJzCdXoT6fjXh/GMjz4aiaRf8SdLoriHICfsOw1MqdcL+dXCVKbqEhNyHOibsSSU0/W6YxLBdSfgap3SMDJMTvJgj9WL07S5YWIqDiNsJnL4Oz4gtmfmBxPim9cAGgwEDthnO6dlwcYLmunVpK6A8RuwB7EpOSA2PAVOthh1scYBzoKJwpJ9Iuoult16dhuxlhG0ZLIQPhszKvVTjDK4mN1KqeeIvkYx8kaoPqi6vQaNiC4wAomPaSr/G6curKE8+64SfEScF2lTuuDVq3a/ao2FxvpxFget2STJXJZrZmr2RwOsM3Ep70Of1gAeiQpnkbQHRvAlfwiKwkommJuxCA/dOY1jCNhZsQrYirA+EqZWkshw+u0uq72h2hFUL1+HL1JFK0pgHLLJ8A0j3m2HCwXQgZRbcob97kGqwVefveoOZNwfkbtEc8N4Uwjg05yZMjGVvYhvosxDNOnM1mjo2ZPwx1/JmM9LmmPCmwdWQ4B2xJVrC5AQWWcsm6Gi6cjD6wfyzPnQ1eHkA22crIbKNTmKYog5Va4IzCPEHay+7YzVcTUTV1eiiiib5A="
  on:
    branch: main

addons:
  sonarcloud:
    organization: "uzhase"
    token:
      secure: WdX/XYwl/r09UjU+bWa3SbpHlKvTqxaYkq+Hs0lzQhDzP9sX/Kjx+/AGXJyANMWCkQpq9gG9VRC39MZuf6HOwfWqnpETE4aX2EnpjgE3DW7tBduVA9yYml3WKZYeKOK6Xd4jPcmQ2Opx5La+iWBELc60HXC0S9K7eBQWlSiZmmQ9i1WByDxwoyqvTM5H0e6Zt3cxlNe3DKS++Rfnl050d7X63f7J/5UdQQ600Mskpphs1vihG0ZqzP9Ex8+v6V4uPEaXwY4/ERFYsc6AaTmgPlHOwi1C/9hXGIn9NHOvYh456lunEji+JKGoRV2bCHxm3oHeURVWyQ2hnWEUQY64ALzIQOzjbzIkPVYeOxO82HBT8Lteh3CgDSZhwvzMB9TPK7NURJ2Dh/x8BzChmcDZT+bOmJNZI3+Hv3lxsc80Erha0HOL5fQ3c2hyHDksjhjmu2J+wibIhcJwvQGeZSjgBhpMOro7JSRQR19TE8UiUHT3NtX0WX1ErFgzqnGbLmG0sPkVLBquY0bAnRS4vBsuYRFGsURfjGtq9+DmcNJjDub/bQUBmU1bEj73MccVhgigN7NUQ7OLl5Td7ZZgpvxFIQp8dwvmkOnRcUeNbRMYPY6MOoXwwiQlcbQ30Pvrr5pHKjtclYeMHtvioOvqfXi4eBReI0rYlF55MPAaDIWDrac=

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script:
  # other script steps might be done before running the actual analysis
  - pytest --cov=server --rootdir=. && coverage xml # set rootdir because of relative path for SQLite connections
  - sonar-scanner

notifications:
  email: false

env:
  global:
    - secure: SONAR_TOKEN=WdX/XYwl/r09UjU+bWa3SbpHlKvTqxaYkq+Hs0lzQhDzP9sX/Kjx+/AGXJyANMWCkQpq9gG9VRC39MZuf6HOwfWqnpETE4aX2EnpjgE3DW7tBduVA9yYml3WKZYeKOK6Xd4jPcmQ2Opx5La+iWBELc60HXC0S9K7eBQWlSiZmmQ9i1WByDxwoyqvTM5H0e6Zt3cxlNe3DKS++Rfnl050d7X63f7J/5UdQQ600Mskpphs1vihG0ZqzP9Ex8+v6V4uPEaXwY4/ERFYsc6AaTmgPlHOwi1C/9hXGIn9NHOvYh456lunEji+JKGoRV2bCHxm3oHeURVWyQ2hnWEUQY64ALzIQOzjbzIkPVYeOxO82HBT8Lteh3CgDSZhwvzMB9TPK7NURJ2Dh/x8BzChmcDZT+bOmJNZI3+Hv3lxsc80Erha0HOL5fQ3c2hyHDksjhjmu2J+wibIhcJwvQGeZSjgBhpMOro7JSRQR19TE8UiUHT3NtX0WX1ErFgzqnGbLmG0sPkVLBquY0bAnRS4vBsuYRFGsURfjGtq9+DmcNJjDub/bQUBmU1bEj73MccVhgigN7NUQ7OLl5Td7ZZgpvxFIQp8dwvmkOnRcUeNbRMYPY6MOoXwwiQlcbQ30Pvrr5pHKjtclYeMHtvioOvqfXi4eBReI0rYlF55MPAaDIWDrac=