language: python
python:
  - "3.9"

deploy:
  provider: heroku
  api_key:
    secure: "HYF/z1pyjETHlGuneA7rK654lqJcC3+5ZhC72xygQ8TtnvCG+XkVzAPnZz5UXKv9oQxsR07LNd4hQJD381/iEc7yG871TbZow33tfhbKjILqww5UoCJzCdXoT6fjXh/GMjz4aiaRf8SdLoriHICfsOw1MqdcL+dXCVKbqEhNyHOibsSSU0/W6YxLBdSfgap3SMDJMTvJgj9WL07S5YWIqDiNsJnL4Oz4gtmfmBxPim9cAGgwEDthnO6dlwcYLmunVpK6A8RuwB7EpOSA2PAVOthh1scYBzoKJwpJ9Iuoult16dhuxlhG0ZLIQPhszKvVTjDK4mN1KqeeIvkYx8kaoPqi6vQaNiC4wAomPaSr/G6curKE8+64SfEScF2lTuuDVq3a/ao2FxvpxFget2STJXJZrZmr2RwOsM3Ep70Of1gAeiQpnkbQHRvAlfwiKwkommJuxCA/dOY1jCNhZsQrYirA+EqZWkshw+u0uq72h2hFUL1+HL1JFK0pgHLLJ8A0j3m2HCwXQgZRbcob97kGqwVefveoOZNwfkbtEc8N4Uwjg05yZMjGVvYhvosxDNOnM1mjo2ZPwx1/JmM9LmmPCmwdWQ4B2xJVrC5AQWWcsm6Gi6cjD6wfyzPnQ1eHkA22crIbKNTmKYog5Va4IzCPEHay+7YzVcTUTV1eiiiib5A="
  on:
    branch: main

addons:
  sonarcloud:
    organization: "uzhase-fs21"
    token:
      secure: cP009y0D/ftpltXV0kL7w2X12YEgQzB9dEU5aoY/QSMRws9vHXXASY1bZ1b0sAE84SZpkUJBymxndCLwdtHPI9BRzOq2QPXlMNnfay3Z9iDyBbFtDQI7dEFi4WhPyjIj+rnj66WFABXNhJeDwkxbzIA/i0qsYzcA4tdbb82d1DaO1+X7QmNL2n5PWh7POnX7s9h3XGLqoeXv0mD59EPL28VIsWWkiN0Hk9LrSJC43ecWqJFwzEDDhLRoS3XzUpW64flUrPPUmn+5EVOCKzzhQoU5cGNsYf+hOjR1g4qyHVz8OTZeeoi1zEqCVDPMsmBey+hX7zsKNp5gHmZaKHD+jQtgkxyNOIG+KG8zFaLL5bTje8TrMfYj7GVc1qQ/6xUPOu53SV6Q93QAHPdKhpyyqL2Z6FMBSnlbbo8WAgAA6gY776loXv7R6HBr21By//wv/ozj4Oqal8GwGV1vM1w7+l1NFrA6hFsu8Z7q4NvJKskfXW0ueggU2OjU3TI0bWJfye7lkh6gZW2Ab2m8TvzKNm9MnzfKf6Req6uMHbC1yyzYd5Sf0fYcCpJQ5TSpXY9ZZhQhNnWh2VTe763bdzWNUjvaG0FGlnEjPiz8QNaqRVvTiUfXVUb6OtiDcWvJaRS7LYtMhO4tyhp7BiRRfuDGbTSK5VYy9eYkW9Ohm/3fg9c=
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script:
  # other script steps might be done before running the actual analysis
  - pytest --cov=server --rootdir=. && coverage xml # set rootdir because of relative path for SQLite connections
  - sonar-scanner

branches:
  only:
    - main
    - dev

notifications:
  email: false

env:
  global:
    - secure: SONAR_TOKEN=cP009y0D/ftpltXV0kL7w2X12YEgQzB9dEU5aoY/QSMRws9vHXXASY1bZ1b0sAE84SZpkUJBymxndCLwdtHPI9BRzOq2QPXlMNnfay3Z9iDyBbFtDQI7dEFi4WhPyjIj+rnj66WFABXNhJeDwkxbzIA/i0qsYzcA4tdbb82d1DaO1+X7QmNL2n5PWh7POnX7s9h3XGLqoeXv0mD59EPL28VIsWWkiN0Hk9LrSJC43ecWqJFwzEDDhLRoS3XzUpW64flUrPPUmn+5EVOCKzzhQoU5cGNsYf+hOjR1g4qyHVz8OTZeeoi1zEqCVDPMsmBey+hX7zsKNp5gHmZaKHD+jQtgkxyNOIG+KG8zFaLL5bTje8TrMfYj7GVc1qQ/6xUPOu53SV6Q93QAHPdKhpyyqL2Z6FMBSnlbbo8WAgAA6gY776loXv7R6HBr21By//wv/ozj4Oqal8GwGV1vM1w7+l1NFrA6hFsu8Z7q4NvJKskfXW0ueggU2OjU3TI0bWJfye7lkh6gZW2Ab2m8TvzKNm9MnzfKf6Req6uMHbC1yyzYd5Sf0fYcCpJQ5TSpXY9ZZhQhNnWh2VTe763bdzWNUjvaG0FGlnEjPiz8QNaqRVvTiUfXVUb6OtiDcWvJaRS7LYtMhO4tyhp7BiRRfuDGbTSK5VYy9eYkW9Ohm/3fg9c=