# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Host(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, name: str=None, num_of_listings: int=None):  # noqa: E501
        """Host - a model defined in Swagger

        :param id: The id of this Host.  # noqa: E501
        :type id: int
        :param name: The name of this Host.  # noqa: E501
        :type name: str
        :param num_of_listings: The num_of_listings of this Host.  # noqa: E501
        :type num_of_listings: int
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'num_of_listings': int
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'num_of_listings': 'numOfListings'
        }

        self._id = id
        self._name = name
        self._num_of_listings = num_of_listings

    @classmethod
    def from_dict(cls, dikt) -> 'Host':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Host of this Host.  # noqa: E501
        :rtype: Host
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Host.


        :return: The id of this Host.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Host.


        :param id: The id of this Host.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Host.


        :return: The name of this Host.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Host.


        :param name: The name of this Host.
        :type name: str
        """

        self._name = name

    @property
    def num_of_listings(self) -> int:
        """Gets the num_of_listings of this Host.


        :return: The num_of_listings of this Host.
        :rtype: int
        """
        return self._num_of_listings

    @num_of_listings.setter
    def num_of_listings(self, num_of_listings: int):
        """Sets the num_of_listings of this Host.


        :param num_of_listings: The num_of_listings of this Host.
        :type num_of_listings: int
        """

        self._num_of_listings = num_of_listings
