# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server.models.base_model_ import Model
from server.models.layer_entry import LayerEntry  # noqa: F401,E501
from server import util


class Layer(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, type: str=None, entries: List[LayerEntry]=None):  # noqa: E501
        """Layer - a model defined in Swagger

        :param type: The type of this Layer.  # noqa: E501
        :type type: str
        :param entries: The entries of this Layer.  # noqa: E501
        :type entries: List[LayerEntry]
        """
        self.swagger_types = {
            'type': str,
            'entries': List[LayerEntry]
        }

        self.attribute_map = {
            'type': 'type',
            'entries': 'entries'
        }
        self._type = type
        self._entries = entries

    @classmethod
    def from_dict(cls, dikt) -> 'Layer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Layer of this Layer.  # noqa: E501
        :rtype: Layer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this Layer.


        :return: The type of this Layer.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this Layer.


        :param type: The type of this Layer.
        :type type: str
        """
        allowed_values = ["crime", "complaints", "health"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def entries(self) -> List[LayerEntry]:
        """Gets the entries of this Layer.


        :return: The entries of this Layer.
        :rtype: List[LayerEntry]
        """
        return self._entries

    @entries.setter
    def entries(self, entries: List[LayerEntry]):
        """Sets the entries of this Layer.


        :param entries: The entries of this Layer.
        :type entries: List[LayerEntry]
        """

        self._entries = entries
